apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: rssmonk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit:latest
        ports:
        - containerPort: 8025
          name: web
        - containerPort: 1025
          name: smtp
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        env:
        - name: MP_UI_BIND_ADDR
          value: "0.0.0.0:8025"
        - name: MP_SMTP_BIND_ADDR
          value: "0.0.0.0:1025"
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
  namespace: rssmonk
spec:
  type: NodePort
  selector:
    app: mailpit
  ports:
  - name: web
    port: 8025
    targetPort: 8025
    nodePort: 30825
  - name: smtp
    port: 1025
    targetPort: 1025
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailpit
  namespace: rssmonk
spec:
  rules:
  - host: mailpit.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mailpit
            port:
              number: 8025
