apiVersion: apps/v1
kind: Deployment
metadata:
  name: listmonk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listmonk-app
  template:
    metadata:
      labels:
        app: listmonk-app
    spec:
      containers:
      - name: listmonk-app
        image: listmonk/listmonk:latest
        env:
        - name: LISTMONK_app__address
          value: "0.0.0.0:9000"
        - name: LISTMONK_db__host
          value: "postgres"
        - name: LISTMONK_db__port
          value: "5432"
        - name: LISTMONK_db__user
          value: "listmonk"
        - name: LISTMONK_db__database
          value: "listmonk"
        - name: LISTMONK_db__password
          value: "listmonk"
        ports:
        - containerPort: 9000
        command:
        - sh
        - -c
        - "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"
---
apiVersion: v1
kind: Service
metadata:
  name: listmonk-service
spec:
  selector:
    app: listmonk-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listmonk
spec:
  rules:
  - host: listmonk.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: listmonk-service
            port:
              number: 80