apiVersion: apps/v1
kind: Deployment
metadata:
  name: listmonk-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listmonk-app
  template:
    metadata:
      labels:
        app: listmonk-app
    spec:
      containers:
      - name: listmonk-app
        image: listmonk/listmonk:v5.1.0
        command: [sh, -c, "./listmonk --install --idempotent --yes --config '' && ./listmonk --upgrade --yes --config '' && ./listmonk --config ''"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: LISTMONK_app__address
          value: "0.0.0.0:9000"
        - name: LISTMONK_db__host
          value: "postgres"
        - name: LISTMONK_db__port
          value: "5432"
        - name: LISTMONK_db__user
          value: "listmonk"
        - name: LISTMONK_db__database
          value: "listmonk"
        - name: LISTMONK_db__password
          valueFrom:
            secretKeyRef:
              name: listmonk-secrets
              key: db-password
        - name: LISTMONK_db__ssl_mode
          value: "disable"
        - name: LISTMONK_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: listmonk-secrets
              key: admin-username
        - name: LISTMONK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: listmonk-secrets
              key: admin-password
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: listmonk-service
spec:
  type: NodePort
  selector:
    app: listmonk-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listmonk
spec:
  rules:
  - host: listmonk.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: listmonk-service
            port:
              number: 80