apiVersion: apps/v1
kind: Deployment
metadata:
  name: rssmonk-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rssmonk-api
  template:
    metadata:
      labels:
        app: rssmonk-api
    spec:
      containers:
        - name: rssmonk-api
          image: rssmonk-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: LISTMONK_URL
              value: "http://listmonk-service:9000"
            - name: LISTMONK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: listmonk-secrets
                  key: admin-username
            - name: LISTMONK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: listmonk-secrets
                  key: admin-password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rssmonk-api
spec:
  type: NodePort
  selector:
    app: rssmonk-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30901
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rssmonk-api
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: rssmonk-api
            port:
              number: 8000
